//==== NEEDED COMPONENTS FOR SHOPPING SCREEN ====//
    /*
    Logo
    USER PORTAL COMPONENT
    FOOTER COMPONENT
    NavBar

    - MENULIST STYLED WITH WHAT IS IN THE CATEGORY LISTS AND ITEM LISTS. 
    - CHECKOUT FEATURE
    - CART FEATURE   
    
    */